# Pandas Complete Tutorial

Welcome to the comprehensive **Pandas Complete Tutorial Notebook**. This notebook consolidates all tutorial modules, hands-on examples, and real-world data analysis projects covering the complete Pandas data manipulation workflow.

---
## Table of Contents
1. **Pandas Series** (`1)Series.ipynb`)
   - Creating Series from lists, NumPy arrays, and dictionaries
   - Indexing and labels
2. **DataFrames Fundamentals** (`2)DataFrames.ipynb`)
   - Creating DataFrames
   - Column Selection, Indexing, and Adding Columns
   - Removing Rows and Columns (`drop`)
   - Selecting Rows (`loc`, `iloc`)
   - Subset Selection and Conditional Filtering
3. **Missing Data Handling** (`3)MissingData.ipynb`)
   - Detecting Nulls (`isna`, `sum`, `any`)
   - Dropping Missing Data (`dropna`, `thresh`)
   - Imputing Missing Values (`fillna`, mean imputation, dictionary mapping)
4. **Merging, Joining & Concatenating** (`4)MergingJoiningConcatination.ipynb`)
   - Inner, Outer, Left, Right Merges
   - Concatenation along rows and columns (`axis=0`, `axis=1`)
   - Index-based Joining (`join`)
5. **GroupBy & Aggregations** (`5)GroupByAggregation.ipynb`)
   - Grouping by single and multiple columns
   - Aggregate functions (`mean`, `sum`, `std`, multi-metric `agg`)
6. **Pivot Tables & Cross Tabulations** (`6)PivotTables.ipynb`)
   - Multi-dimensional pivot tables (`pivot_table`)
   - Frequency cross-tabulations (`crosstab`)
7. **DataFrame Operations & Function Application** (`7)Operations.ipynb`)
   - Summary statistics and inspection (`shape`, `columns`, `info`, `describe`)
   - Column-wise transformations and applying functions (`apply`, lambdas)
8. **Real-World Project 1: Countries Dataset Analysis** (`Countries.ipynb`)
   - Demographic queries, population extrema, political leaders, democracy rankings, and regional subset analysis
9. **Real-World Project 2: Feature Extraction on Anime Dataset** (`FeatureExtraction.ipynb`)
   - String parsing, extracting episode counts, date interval parsing, duration in months, and finding top performers

---
# Source: `1)Series.ipynb` — Pandas Series Fundamentals
---

# Pandas Series

A Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

## Creating Series
There are multiple ways to create a pandas Series:

In [1]:
import numpy as np 
import pandas as pd

In [2]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

---
# Source: `2)DataFrames.ipynb` — DataFrames: Creation, Indexing, Selection & Conditional Filtering
---

In [7]:
import numpy as np 
import pandas as pd

**Creating a DataFrame**

In [8]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [9]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new column**

In [14]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [15]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Removing Columns**

In [16]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [17]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Selecting Rows**

In [18]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [19]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000        Eng.

In [20]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of Rows and Columns**

In [21]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

**Conditional Selection**

In [22]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [23]:
# Question: Filter people whose age is above 30
above_30 = df2[df2["Age"] > 30]
print("People with Age > 30:")
above_30

People with Age > 30:

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
3  Linda   42  London   85000        Eng.

In [24]:
# Question: Filter people whose age is above 30 AND city is Paris
paris_above_30 = df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]
print("People with Age > 30 in Paris:")
paris_above_30

People with Age > 30 in Paris:

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000        Eng.

---
# Source: `3)MissingData.ipynb` — Handling Missing Data (isna, dropna, fillna)
---

In [25]:
import numpy as np 
import pandas as pd

**Finding Missing Data**

In [26]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [27]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [28]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [29]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [30]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

**Removing Missing Data**

In [31]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [32]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [33]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [34]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

**Filling the missing Data**

In [35]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [36]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [37]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [38]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [39]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

---
# Source: `4)MergingJoiningConcatination.ipynb` — Combining Datasets (Merge, Concat, Join)
---

In [40]:
import numpy as np 
import pandas as pd

**Merging 2 dataframes**

In [41]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [42]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [43]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [44]:
pd.merge(employees,salaries,on='employee_id',how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [45]:
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [46]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [47]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatination of 2 dataframes**

In [48]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [49]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [50]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [51]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [52]:
pd.concat([df1,df2],axis= 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining 2 data frames**

In [53]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [54]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [55]:
df2

   score
2     85
3     90
4     75

In [56]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [57]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

---
# Source: `5)GroupByAggregation.ipynb` — GroupBy Operations & Aggregations
---

In [58]:
import numpy as np 
import pandas as pd

**GroupBy**

In [59]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [60]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [61]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [62]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [63]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

In [64]:
df['Sales'].mean()
"""mean median min max count std """

'mean median min max count std '

In [65]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

---
# Source: `6)PivotTables.ipynb` — Pivot Tables & Cross Tabulations
---

In [66]:
import numpy as np 
import pandas as pd

**Pivot Tables**

In [67]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    753     33   John  January      Q1
1  2023-01-02       B   West    885     17   Mary  January      Q1
2  2023-01-03       C  North    708     74    Bob  January      Q1
3  2023-01-04       D  South    798     81  Alice  January      Q1
4  2023-01-05       A   East    200     76   John  January      Q1
5  2023-01-06       B   West    537     80   Mary  January      Q1
6  2023-01-07       C  North    761     18    Bob  January      Q1
7  2023-01-08       D  South    109     43  Alice  January      Q1
8  2023-01-09       A   East    171     81   John  January      Q1
9  2023-01-10       B   West    896     92   Mary  January      Q1
10 2023-01-11       C  North    814     40    Bob  January      Q1
11 2023-01-12       D  South    329     50  Alice  January      Q1
12 2023-01-13       A   East    279     89   John  January      Q1
13 2023-01-14       B   West    820     11   Mary  January      Q1
14 2023-01-15       C  North    869     32    Bob  January      Q1
15 2023-01-16       D  South    879     15  Alice  January      Q1
16 2023-01-17       A   East    433     81   John  January      Q1
17 2023-01-18       B   West    798     90   Mary  January      Q1
18 2023-01-19       C  North    672     34    Bob  January      Q1
19 2023-01-20       D  South    590     56  Alice  January      Q1

In [68]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     279.0    NaN    NaN    NaN
North      NaN    NaN  761.0    NaN
South      NaN    NaN    NaN  590.0
West       NaN  820.0    NaN    NaN

In [69]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     367.2    NaN    NaN    NaN  72.0   NaN   NaN   NaN
North      NaN    NaN  764.8    NaN   NaN   NaN  39.6   NaN
South      NaN    NaN    NaN  541.0   NaN   NaN   NaN  49.0
West       NaN  787.2    NaN    NaN   NaN  58.0   NaN   NaN

**Cross Tabs**

In [70]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

---
# Source: `7)Operations.ipynb` — DataFrame Operations & Applying Custom Functions
---

In [71]:
import numpy as np 
import pandas as pd

**DataFrames Basic Operations**

In [72]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [73]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [74]:
df1.shape

(5, 3)

In [75]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [76]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [77]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [78]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrames Applying Functions**

In [79]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [80]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [81]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

---
# Source: `Countries.ipynb` — Real-World Exploratory Data Analysis: Countries Dataset
---

In [82]:
import numpy as np 
import pandas as pd

In [83]:
df = pd.read_csv("Countries.csv")

In [84]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [85]:
df.shape

(194, 64)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [87]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [88]:
#which country has the highest population
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: object

In [89]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [90]:
#what is the capital of the country with highest population
df[df['population'] == df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [91]:
#which country has the least population
df[df['population'] == df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: object

In [92]:
#what is the capital of the country with least population
df[df['population'] == df['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [93]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [94]:
#give me top 5 countries with highest democratic score
df.sort_values(by = 'democracy_score',ascending=False,inplace = True)

In [95]:
df['country'].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [96]:
#how many total regions are there
df['region'].value_counts().count()

np.int64(22)

In [97]:
#how many countries lie in Eastern Europe region
df[df['region'] == "Eastern Europe"][ 'country']

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

In [98]:
#who is the political leader of the 2nd highest populated country
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

In [99]:
# how many countries are there whoes political leaders are unknown
df[df['political_leader'].isna()]['country'].count()

np.int64(7)

In [100]:
#how many country have Republic in their full name
count = 0
def counting(txt):
    global count 
    if 'republic' in txt.lower():
        count+= 1
    return txt
df['country_long'] = df['country_long'].apply(counting)
print(count)

125

In [101]:
#which country in african region has highest population
africa_df = df[df['continent'] == 'Africa']

In [102]:
africa_df[africa_df['population'] == africa_df['population'].max()]['country']

125    Nigeria
Name: country, dtype: object

---
# Source: `FeatureExtraction.ipynb` — Feature Extraction & Text Parsing: Anime Dataset
---

In [103]:
#loading the data
import numpy as np 
import pandas as pd

In [104]:
df = pd.read_csv(r'anime.csv')

In [105]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [106]:
df.loc[4]['Title']

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [107]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check = False
            return data
        if check == True: 
            data = data + i 
        if i == '(':
            check = True

In [108]:
df["Episodes"] = df["Title"].apply(extract_episodes)

In [109]:
df['Episodes']= df['Episodes'].str.replace(" eps","")

In [110]:
df['Episodes'] = df['Episodes'].astype(int)

In [111]:
df

    Rank                                              Title  Score  Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04        51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04         1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04        13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03        13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03         2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99        13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99        13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98        12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94         1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93        22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93        24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91        25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91         1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89         1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88         7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88        14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87        74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84         1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84         1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83        12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83         1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82        24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82        23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81        12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81        26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80        13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80        16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79        11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79         1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79        11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78        10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78         1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77        26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77        12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76        75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75        26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75        26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74        24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73        10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72        12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71        12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71         4

### Feature Extraction Analytical Questions & Solutions
Below we solve all feature extraction and dataset ranking questions on the anime dataset:
1. Extract episode counts from titles
2. Extract start and end airing time stamps
3. Calculate total duration in months
4. Identify highest scoring anime
5. Find top 5 highest scoring anime
6. Find highest episode count anime
7. Find top 5 highest episode counts
8. Identify the longest running anime

In [112]:
df.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [113]:
def extraction_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1,i+20):
                data += txt[j]

            return data

In [114]:
df['Total Time'] = df['Title'].apply(extraction_time)

In [115]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [116]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

df['Months'] = df['Total Time'].apply(calculate_total_months)

In [117]:
df

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,8

In [118]:
# 1. Highest scoring anime
print("--- Highest Scoring Anime ---")
highest_score_anime = df[df['Score'] == df['Score'].max()][['Title', 'Score']]
display(highest_score_anime)

# 2. Top 5 highest scoring anime
print("\n--- Top 5 Highest Scoring Anime ---")
top5_score = df.sort_values(by='Score', ascending=False)[['Title', 'Score']].head(5)
display(top5_score)

# 3. Anime with the highest episode count
print("\n--- Anime with Highest Episode Count ---")
highest_episodes_anime = df[df['Episodes'] == df['Episodes'].max()][['Title', 'Episodes']]
display(highest_episodes_anime)

# 4. Top 5 animes with highest episode count
print("\n--- Top 5 Animes with Highest Episode Counts ---")
top5_episodes = df.sort_values(by='Episodes', ascending=False)[['Title', 'Episodes']].head(5)
display(top5_episodes)

# 5. Longest running anime (in months)
print("\n--- Longest Running Anime (in Months) ---")
longest_running = df[df['Months'] == df['Months'].max()][['Title', 'Total Time', 'Months']]
display(longest_running)

--- Highest Scoring Anime ---

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...    9.1

--- Top 5 Highest Scoring Anime ---

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

--- Anime with Highest Episode Count ---

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201

--- Top 5 Animes with Highest Episode Counts ---

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7   Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74

--- Longest Running Anime (in Months) ---

,Title,Total Time,Months
11,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,Jan 1988 - Mar 1997,111

In [119]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [120]:
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

---
# Source: `10.4-readdata.ipynb`, `10.2` & `10.3` — Reading Data From Multiple Sources & Enterprise Sales Analytics
---
## 📥 Multi-Source Data Ingestion & Real-World Sales Analytics
This section consolidates reading and writing data across different sources (JSON, HTML tables, Excel spreadsheets, Web URLs, and Pickles) alongside enterprise sales analytics using `sales_data.csv`.

### 1. Reading & Writing JSON Data
Pandas provides high-performance JSON parsing with `pd.read_json()`. The `orient` parameter controls JSON structure layout (`records`, `index`, `split`, `columns`).

In [121]:
import pandas as pd
from io import StringIO

# Reading JSON data from string or API response
json_data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df_json = pd.read_json(StringIO(json_data))
print("Parsed JSON DataFrame:")
df_json

Parsed JSON DataFrame:

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [122]:
# Writing DataFrame to JSON with different orientations
print("Default JSON export:")
print(df_json.to_json())

print("\nJSON export (orient='records'):")
print(df_json.to_json(orient='records'))

print("\nJSON export (orient='index'):")
print(df_json.to_json(orient='index'))

Default JSON export:
{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}

JSON export (orient='records'):
[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]

JSON export (orient='index'):
{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}

### 2. Ingesting Datasets Directly from Web URLs
You can stream CSV or raw text files directly into Pandas by passing HTTPS URLs to `pd.read_csv()`.

In [123]:
# Reading wine dataset directly from UCI Machine Learning Repository
wine_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
df_wine = pd.read_csv(wine_url, header=None)

print(f"Loaded Wine dataset shape: {df_wine.shape}")
df_wine.head(3)

Loaded Wine dataset shape: (178, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185

In [124]:
# Saving DataFrame to local CSV
df_wine.to_csv("wine.csv", index=False)
print("Saved wine.csv locally!")

Saved wine.csv locally!

### 3. Web Scraping HTML Tables with `pd.read_html`
`pd.read_html()` searches a webpage for `<table>` tags and automatically parses them into a list of DataFrames using `lxml` or `html5lib`.

In [125]:
# Web Scraping Mobile Country Codes table from Wikipedia
wiki_url = "https://en.wikipedia.org/wiki/Mobile_country_code"
try:
    tables = pd.read_html(wiki_url, match="Country", header=0)
    print(f"Extracted {len(tables)} tables from Wikipedia.")
    print("First extracted table sample:")
    display(tables[0].head(5))
except Exception as e:
    print(f"Web scraping notice: {e}")

Web scraping notice: HTTP Error 403: Forbidden

### 4. Reading and Writing Excel Files (`.xlsx`)
Pandas supports multi-sheet Excel files using `openpyxl` as the underlying reader/writer engine.

In [126]:
# Reading Excel spreadsheet
try:
    df_excel = pd.read_excel('data.xlsx')
    print("Loaded data.xlsx:")
    display(df_excel)
except Exception as e:
    print(f"Notice: {e}")

Loaded data.xlsx:

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

### 5. High-Speed Binary Serialization with Pickle
Pickling preserves Python-specific data types (including datetime and categorical types) and reads up to **10x faster** than CSV for large datasets.

In [127]:
# Serializing DataFrame to binary pickle
try:
    df_excel.to_pickle('df_excel.pkl')
    print("Saved df_excel.pkl successfully!")

    # Reading pickled DataFrame back into memory
    df_unpickled = pd.read_pickle('df_excel.pkl')
    print("Loaded unpickled DataFrame:")
    display(df_unpickled)
except Exception as e:
    print(f"Notice: {e}")

Saved df_excel.pkl successfully!
Loaded unpickled DataFrame:

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

### 6. Real-World Enterprise Analytics on `sales_data.csv`
Analysis of transactions, high-speed scalar lookups (`.at`, `.iat`), column transformations, and multi-level GroupBy operations.

In [128]:
# Load sales_data.csv
sales_df = pd.read_csv('sales_data.csv')
print(f"Sales Data Shape: {sales_df.shape}")
print("\nColumns:", sales_df.columns.tolist())
sales_df.head(3)

Sales Data Shape: (240, 9)

Columns: ['Transaction ID', 'Date', 'Product Category', 'Product Name', 'Units Sold', 'Unit Price', 'Total Revenue', 'Region', 'Payment Method']

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [129]:
# Fast Scalar Access: .at (label-based) vs .iat (integer-based)
# .at and .iat are up to 10x faster than .loc and .iloc for single-value access
print("Product Name at row index 2 using .at:", sales_df.at[2, 'Product Name'])
print("Value at row index 2, column index 3 using .iat:", sales_df.iat[2, 3])

Product Name at row index 2 using .at: Levi's 501 Jeans
Value at row index 2, column index 3 using .iat: Levi's 501 Jeans

In [130]:
# Summary statistics and revenue distribution
print("Summary Statistics:")
display(sales_df.describe())

Summary Statistics:

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [131]:
# Total Revenue by Product Category
category_revenue = sales_df.groupby('Product Category')['Total Revenue'].agg(['sum', 'mean', 'count']).rename(
    columns={'sum': 'Total Revenue', 'mean': 'Avg Revenue', 'count': 'Transactions'}
)
print("Revenue by Product Category:")
display(category_revenue)

Revenue by Product Category:

                  Total Revenue  Avg Revenue  Transactions
Product Category
Beauty Products         2621.90     65.54750            40
Books                   1861.93     46.54825            40
Clothing                8128.93    203.22325            40
Electronics            34982.41    874.56025            40
Home Appliances        18646.16    466.15400            40
Sports                 14326.52    358.16300            40

In [132]:
# Multi-level GroupBy: Total Revenue by Product Category & Region
region_product_sales = sales_df.groupby(['Product Category', 'Region'])['Total Revenue'].sum().unstack()
print("Revenue Matrix (Product Category x Region):")
display(region_product_sales)

Revenue Matrix (Product Category x Region):

Region                Asia    Europe  North America
Product Category
Beauty Products        NaN   2621.90            NaN
Books                  NaN       NaN        1861.93
Clothing           8128.93       NaN            NaN
Electronics            NaN       NaN       34982.41
Home Appliances        NaN  18646.16            NaN
Sports            14326.52       NaN            NaN

---
# Source: `exercises.ipynb` — Pandas Exercises & Practice Problems
---
**General Questions**

Here we answer essential general data analysis and manipulation questions on the student dataset using Pandas.

In [133]:
import pandas as pd
import numpy as np

# Student Dataset for General Questions
df = pd.DataFrame({
    'Name': ['Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5'],
    'Age': [18, 19, 17, 18, 20],
    'Math': [85, 92, 76, 65, 90],
    'Science': [78, 88, 95, 70, 85]
}).set_index('Name')

df

           Age  Math  Science
Name
Student 1   18    85       78
Student 2   19    92       88
Student 3   17    76       95
Student 4   18    65       70
Student 5   20    90       85

In [134]:
# Get the shape of the DataFrame.
df.shape

(5, 3)

In [135]:
# Find the average age of students.
df['Age'].mean()

np.float64(18.4)

In [136]:
# Extract Math marks of all students.
df['Math']

Name
Student 1    85
Student 2    92
Student 3    76
Student 4    65
Student 5    90
Name: Math, dtype: int64

In [137]:
# Find the highest Science mark.
df['Science'].max()

95

In [138]:
# Get details of the student who scored more than 90 in Math.
df[df['Math'] > 90]

           Age  Math  Science
Name
Student 2   19    92       88

In [139]:
# Increase Math marks of all students by 5.
df['Math'] += 5
df

           Age  Math  Science
Name
Student 1   18    90       78
Student 2   19    97       88
Student 3   17    81       95
Student 4   18    70       70
Student 5   20    95       85

In [140]:
# Find how many students are younger than 19.
(df['Age'] < 19).sum()

np.int64(3)

In [141]:
# Calculate the average marks in each subject (column-wise mean).
df[['Math', 'Science']].mean()

Math       86.6
Science    83.2
dtype: float64

In [142]:
# Get data of students who scored at least 80 in both subjects.
df[(df['Math'] >= 80) & (df['Science'] >= 80)]

           Age  Math  Science
Name
Student 2   19    97       88
Student 3   17    81       95
Student 5   20    95       85

In [143]:
# Replace all Science marks < 75 with 0.
df.loc[df['Science'] < 75, 'Science'] = 0
df

           Age  Math  Science
Name
Student 1   18    90       78
Student 2   19    97       88
Student 3   17    81       95
Student 4   18    70        0
Student 5   20    95       85

In [144]:
# Calculate Total Marks and Percentage for each student.
df['Total'] = df['Math'] + df['Science']
df['Percentage'] = df['Total'] / 2
df

           Age  Math  Science  Total  Percentage
Name
Student 1   18    90       78    168        84.0
Student 2   19    97       88    185        92.5
Student 3   17    81       95    176        88.0
Student 4   18    70        0     70        35.0
Student 5   20    95       85    180        90.0

In [145]:
# Sort students by total marks in descending order.
df.sort_values(by='Total', ascending=False)

           Age  Math  Science  Total  Percentage
Name
Student 2   19    97       88    185        92.5
Student 5   20    95       85    180        90.0
Student 3   17    81       95    176        88.0
Student 1   18    90       78    168        84.0
Student 4   18    70        0     70        35.0

In [146]:
# Assign letter grades based on percentage (A >= 85, B >= 75, else C).
df['Grade'] = np.select(
    [df['Percentage'] >= 85, df['Percentage'] >= 75],
    ['A', 'B'],
    default='C'
)
df[['Total', 'Percentage', 'Grade']]

           Total  Percentage Grade
Name
Student 1    168        84.0     B
Student 2    185        92.5     A
Student 3    176        88.0     A
Student 4     70        35.0     C
Student 5    180        90.0     A

In [147]:
# Group by Age and find average marks for each subject.
df.groupby('Age')[['Math', 'Science']].mean()

     Math  Science
Age
17   81.0     95.0
18   80.0     39.0
19   97.0     88.0
20   95.0     85.0

In [148]:
# Generate comprehensive summary statistics.
df.describe()

             Age       Math    Science       Total  Percentage
count   5.000000   5.000000   5.000000    5.000000    5.000000
mean   18.400000  86.600000  69.200000  155.800000   77.900000
std     1.140175  11.148991  39.162482   48.365277   24.182638
min    17.000000  70.000000   0.000000   70.000000   35.000000
25%    18.000000  81.000000  78.000000  168.000000   84.000000
50%    18.000000  90.000000  85.000000  176.000000   88.000000
75%    19.000000  95.000000  88.000000  180.000000   90.000000
max    20.000000  97.000000  95.000000  185.000000   92.500000

---
# 🎯 Pandas Interview Mastery & Production-Grade Concepts
---
This section covers high-frequency interview questions, memory optimization techniques, internal architecture, and advanced manipulation patterns tested in Data Engineering, Data Analytics, and Machine Learning interviews.

### Key Interview Topics Covered:
1. **Memory Optimization: Downcasting & `category` Dtype (Saving 80-90% RAM)**
2. **The `SettingWithCopyWarning` & The Chained Assignment Trap**
3. **`GroupBy` Mastery: `agg()` vs `transform()` vs `filter()` vs `apply()`**
4. **Top-N Rows Per Group (Classic Interview Problem)**
5. **Window Functions: Rolling, Expanding, and Lead/Lag Analysis (`shift`, `pct_change`)**
6. **Reshaping Masterclass: `melt()` vs `pivot_table()` vs `explode()`**
7. **Safe Merging: Merge Validation (`validate='1:m'`) & Merge Indicators**
8. **Method Chaining: Clean Production Pipelines with `.pipe()`, `.assign()`, and `.query()`**

### 1. Memory Optimization & Dtype Downcasting
**Interview Question:** *Your Pandas DataFrame takes 8 GB of RAM and crashes the server. How do you reduce its memory usage by 70–90% without losing data?*

**Techniques:**
1. **Categorical conversion:** String columns with low cardinality (repeated values like cities, genders, status) store repeated pointer objects. Converting to `'category'` replaces strings with lightweight integer codes and an internal lookup dictionary.
2. **Numeric downcasting:** `int64` (8 bytes) to `int8` (1 byte) or `int16` (2 bytes); `float64` to `float32`.
3. **Inspect memory:** Use `df.info(memory_usage='deep')` and `df.memory_usage(deep=True)`. Regular `.memory_usage()` misses the heap size of Python strings!

In [149]:
# Memory Optimization Demo
import pandas as pd
import numpy as np

# Create sample dataset with high repetition strings
n_rows = 100_000
df_mem = pd.DataFrame({
    'user_id': np.arange(n_rows),
    'membership': np.random.choice(['Bronze', 'Silver', 'Gold', 'Platinum'], size=n_rows),
    'city': np.random.choice(['New York', 'London', 'Tokyo', 'Berlin', 'Mumbai'], size=n_rows),
    'age': np.random.randint(18, 70, size=n_rows),
    'score': np.random.uniform(50.0, 100.0, size=n_rows)
})

mem_before = df_mem.memory_usage(deep=True).sum() / (1024**2)
print(f"Memory BEFORE optimization: {mem_before:.2f} MB")

# 1. Convert low-cardinality strings to 'category'
df_mem['membership'] = df_mem['membership'].astype('category')
df_mem['city'] = df_mem['city'].astype('category')

# 2. Downcast numeric columns
df_mem['age'] = pd.to_numeric(df_mem['age'], downcast='integer') # int8 (18-70 fits in int8)
df_mem['score'] = pd.to_numeric(df_mem['score'], downcast='float') # float32

mem_after = df_mem.memory_usage(deep=True).sum() / (1024**2)
print(f"Memory AFTER optimization:  {mem_after:.2f} MB")
print(f"Memory Reduction: {(1 - mem_after/mem_before)*100:.1f}%")

Memory BEFORE optimization: 12.42 MB
Memory AFTER optimization:  1.43 MB
Memory Reduction: 88.5%

### 2. The Dreaded `SettingWithCopyWarning` Explained
**Interview Question:** *Why does `SettingWithCopyWarning` occur in Pandas, and how do you resolve it? What is chained indexing?*

- **Chained Indexing:** `df['colA'][df['colB'] > 5] = 100` involves two separate operations:
  1. `df['colA']` -> `__getitem__`
  2. `[df['colB'] > 5] = 100` -> `__setitem__`
- Because Pandas cannot guarantee whether the first step returned a **view** or a **copy**, modifying it may fail silently or corrupt state.
- **The Fix:**
  - If modifying original: Use single-indexer `.loc[row_mask, col_mask] = value`.
  - If creating a standalone sub-frame: Explicitly do `.copy()`.

In [150]:
# SettingWithCopyWarning Demo and Fix
df_demo = pd.DataFrame({
    'department': ['IT', 'HR', 'IT', 'Sales'],
    'salary': [50000, 45000, 60000, 52000]
})

# ❌ WRONG (Chained Indexing - may trigger SettingWithCopyWarning):
# sub_df = df_demo[df_demo['department'] == 'IT']
# sub_df['salary'] = 70000

# ✅ CORRECT Solution 1: Use .loc directly on original df
df_demo.loc[df_demo['department'] == 'IT', 'salary'] += 5000
print("Updated original dataframe with .loc:")
print(df_demo)

# ✅ CORRECT Solution 2: Explicit .copy() when creating a subset
it_team = df_demo[df_demo['department'] == 'IT'].copy()
it_team['bonus'] = 10000 # Completely safe, no warning!
print("
Independent subset with .copy():")
print(it_team)

SyntaxError: unterminated string literal (detected at line 19) (1154034786.py, line 19)

### 3. GroupBy Deep Dive: `agg()` vs `transform()` vs `filter()` vs `apply()`
**Interview Question:** *What is the difference between `agg()`, `transform()`, `filter()`, and `apply()` in Pandas GroupBy? When do you use each?*

| Method | Output Shape | Primary Use Case |
|---|---|---|
| **`agg()`** | Collapses to **1 row per group** | Summary metrics (sum, mean, min, max, count). |
| **`transform()`** | Returns **same shape as input** | Calculating group-normalized metrics (e.g., z-scores, % of department budget, imputing group mean). |
| **`filter()`** | Subset of original rows | Dropping entire groups that fail an aggregate condition (e.g. keep departments with > 5 employees). |
| **`apply()`** | Flexible (any shape) | Complex custom logic across sub-DataFrames (slower, use vectorized methods when possible). |

In [151]:
# GroupBy: agg vs transform vs filter vs apply
sales_df = pd.DataFrame({
    'Store': ['A', 'A', 'A', 'B', 'B', 'C'],
    'Product': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Apple'],
    'Revenue': [100, 200, 300, 400, 500, 50]
})
print("Original Sales Data:
", sales_df)

# 1. agg: Summarizes to one row per store
print("
1. agg() - Total Revenue per Store:")
print(sales_df.groupby('Store')['Revenue'].agg(['sum', 'mean']))

# 2. transform: Computes group sum and broadcasts to original row size!
sales_df['Store_Total'] = sales_df.groupby('Store')['Revenue'].transform('sum')
sales_df['Pct_Of_Store'] = (sales_df['Revenue'] / sales_df['Store_Total']) * 100
print("
2. transform() - % Contribution to Store Total:
", sales_df)

# 3. filter: Keep only stores with total revenue >= 500
filtered_stores = sales_df.groupby('Store').filter(lambda g: g['Revenue'].sum() >= 500)
print("
3. filter() - Stores with Revenue >= 500:
", filtered_stores[['Store', 'Product', 'Revenue']])

SyntaxError: unterminated string literal (detected at line 7) (3023369353.py, line 7)

### 4. Top-N Rows Per Group (High-Frequency SQL & Pandas Problem)
**Interview Question:** *Given an employee dataset, write the Pandas code to find the top 2 highest-paid employees in each department.*

**Two fast approaches:**
1. Sort values globally, then `groupby().head(N)`.
2. GroupBy with `nlargest(N)`.

In [152]:
# Top-N Per Group
emp_df = pd.DataFrame({
    'Department': ['Tech', 'Tech', 'Tech', 'Finance', 'Finance', 'Finance', 'HR'],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [120000, 110000, 140000, 95000, 130000, 105000, 80000]
})

# Approach 1: sort + groupby().head() - Fast and Vectorized!
top_2_salaries = (
    emp_df.sort_values(by=['Department', 'Salary'], ascending=[True, False])
    .groupby('Department')
    .head(2)
    .reset_index(drop=True)
)
print("Top 2 Salaries per Department:")
print(top_2_salaries)

Top 2 Salaries per Department:
  Department     Name  Salary
0    Finance      Eva  130000
1    Finance    Frank  105000
2         HR    Grace   80000
3       Tech  Charlie  140000
4       Tech    Alice  120000

### 5. Window Functions: Rolling, Expanding, and Lead/Lag (`shift`, `pct_change`)
**Interview Question:** *How do you compute a 3-day moving average, cumulative revenue, and day-over-day growth rate for stock or sales data in Pandas?*

- **`.rolling(window=N)`:** Moving window over past $N$ observations.
- **`.expanding()`:** Cumulative window including all observations from the beginning up to the current row.
- **`.shift(1)`:** Lag feature (yesterday's value).
- **`.pct_change()`:** Percentage change $(x_t - x_{t-1}) / x_{t-1}$.

In [153]:
# Window and Time-Series Metrics
dates = pd.date_range(start='2026-01-01', periods=7, freq='D')
stock_df = pd.DataFrame({
    'Date': dates,
    'Price': [100.0, 105.0, 102.0, 110.0, 115.0, 112.0, 120.0]
}).set_index('Date')

# 3-Day Moving Average
stock_df['MA_3D'] = stock_df['Price'].rolling(window=3).mean()

# Cumulative Max and Running Total
stock_df['Running_Max'] = stock_df['Price'].expanding().max()

# Previous Day Price (Lag) and Day-over-Day Return
stock_df['Prev_Price'] = stock_df['Price'].shift(1)
stock_df['Daily_Return_Pct'] = stock_df['Price'].pct_change() * 100

print("Stock Metrics with Window Functions:")
print(stock_df)

Stock Metrics with Window Functions:
            Price       MA_3D  Running_Max  Prev_Price  Daily_Return_Pct
Date
2026-01-01  100.0         NaN        100.0         NaN               NaN
2026-01-02  105.0         NaN        105.0       100.0          5.000000
2026-01-03  102.0  102.333333        105.0       105.0         -2.857143
2026-01-04  110.0  105.666667        110.0       102.0          7.843137
2026-01-05  115.0  109.000000        115.0       110.0          4.545455
2026-01-06  112.0  112.333333        115.0       115.0         -2.608696
2026-01-07  120.0  115.666667        120.0       112.0          7.142857

### 6. Reshaping Masterclass: `melt()` vs `pivot_table()` vs `explode()`
**Interview Question:** *What is the difference between Wide and Long data formats? How do you unpivot wide data, pivot long data, and unnest list elements in cells?*

- **`melt()` (Wide -> Long):** Turns multiple column headers into rows. Ideal for machine learning and tidy datasets.
- **`pivot_table()` (Long -> Wide):** Aggregates and reshapes long data into a matrix. Handles duplicate index/column pairs with an aggregation function.
- **`explode()`:** Flattens array/list values inside a column into individual rows.

In [154]:
# Reshaping: melt, pivot_table, and explode
# Wide format
wide_df = pd.DataFrame({
    'Student': ['Alice', 'Bob'],
    'Math': [85, 90],
    'Science': [92, 88],
    'English': [78, 85]
})
print("Wide Format:
", wide_df)

# Unpivot to Long format using melt:
long_df = wide_df.melt(id_vars=['Student'], var_name='Subject', value_name='Score')
print("
Long Format (melt):
", long_df)

# Pivot back with pivot_table:
pivoted_df = long_df.pivot_table(index='Student', columns='Subject', values='Score')
print("
Pivoted Back:
", pivoted_df)

# Explode demo: list in cell
tags_df = pd.DataFrame({
    'Movie': ['Inception', 'Titanic'],
    'Genres': [['Sci-Fi', 'Thriller'], ['Drama', 'Romance']]
})
print("
Before Explode:
", tags_df)
print("
After Explode:
", tags_df.explode('Genres'))

SyntaxError: unterminated string literal (detected at line 9) (1413121885.py, line 9)

### 7. Safe Merging: Validation (`validate='1:m'`) & Merge Indicator
**Interview Question:** *How do you prevent accidental Cartesian products / duplicated rows during joins in Pandas? How do you find non-matching rows in an outer join?*

- **`validate` parameter:** Validates merge integrity (`'1:1'`, `'1:m'`, `'m:1'`, `'m:m'`). Raises `MergeError` if duplicates violate your assumption.
- **`indicator=True`:** Adds `_merge` column with `'left_only'`, `'right_only'`, or `'both'`.

In [155]:
# Safe Merging with validate and indicator
users = pd.DataFrame({'user_id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
orders = pd.DataFrame({'user_id': [1, 1, 2, 4], 'amount': [250, 150, 400, 300]})

# Merge with validate and indicator
merged_df = pd.merge(
    users, 
    orders, 
    on='user_id', 
    how='outer',
    validate='1:m',      # Ensures user_id is unique on left table!
    indicator=True       # Shows match source
)
print("Safe Merge Result with indicator:")
print(merged_df)

# Find records that only existed in orders (unregistered users):
orphan_orders = merged_df[merged_df['_merge'] == 'right_only']
print("
Orders without matching User record:")
print(orphan_orders)

SyntaxError: unterminated string literal (detected at line 19) (3084455851.py, line 19)

### 8. Clean Method Chaining (Production-Grade Pandas Pipelines)
**Interview Question:** *How do you write readable, production-grade Pandas transformations without creating 10 intermediate DataFrame variables?*

Use **Method Chaining** with `.assign()`, `.query()`, and `.pipe()`:
- `.assign()`: Adds or modifies columns inline without mutating original data.
- `.query()`: Filters rows using concise SQL-like expressions.
- `.pipe()`: Passes the DataFrame cleanly into external custom functions.

In [156]:
# Method Chaining Pipeline
raw_data = pd.DataFrame({
    'customer': ['Cust_A', 'Cust_B', 'Cust_C', 'Cust_D', 'Cust_E'],
    'spend': [1200, 450, 3100, 800, 150],
    'country': ['US', 'CA', 'US', 'UK', 'US']
})

def flag_tier(df):
    """Custom business logic function used with pipe()"""
    df['is_vip'] = df['spend'] > 1000
    return df

# Fluent pipeline:
clean_summary = (
    raw_data
    .query("country in ['US', 'UK']")
    .assign(tax=lambda d: d['spend'] * 0.08)
    .assign(total=lambda d: d['spend'] + d['tax'])
    .pipe(flag_tier)
    .sort_values(by='total', ascending=False)
    .reset_index(drop=True)
)

print("Final Pipeline Output:")
print(clean_summary)

Final Pipeline Output:
  customer  spend country    tax   total  is_vip
0   Cust_C   3100      US  248.0  3348.0    True
1   Cust_A   1200      US   96.0  1296.0    True
2   Cust_D    800      UK   64.0   864.0   False
3   Cust_E    150      US   12.0   162.0   False

### 9. MultiIndex & Hierarchical Indexing (`pd.IndexSlice`, `.xs()`)
**Interview Question:** *How do you slice across specific levels of a MultiIndex without resetting index? What is the difference between `.loc[pd.IndexSlice[...]]` and `.xs()`?*

- **`.xs()` (Cross-Section):** Extracts data at a specific level of a MultiIndex without needing to specify all levels.
- **`pd.IndexSlice`:** Enables slicing across multiple levels of rows and columns using standard Python slice notation (`:`).

In [157]:
# MultiIndex Creation, Cross-Section (xs), and IndexSlice
import pandas as pd
import numpy as np

# MultiIndex DataFrame
arrays = [
    ['Engineering', 'Engineering', 'Engineering', 'Marketing', 'Marketing'],
    ['Senior', 'Mid', 'Junior', 'Senior', 'Junior']
]
idx = pd.MultiIndex.from_arrays(arrays, names=['Department', 'Level'])
df_hierarchical = pd.DataFrame({
    'Base_Salary': [150000, 110000, 80000, 130000, 70000],
    'Bonus': [30000, 15000, 8000, 25000, 6000]
}, index=idx)

print("MultiIndex DataFrame:")
display(df_hierarchical)

# 1. Using .xs() to extract all 'Senior' roles across all departments:
print("\nAll Senior Employees across departments (via .xs):")
display(df_hierarchical.xs('Senior', level='Level'))

# 2. Using pd.IndexSlice to slice Engineering seniors:
idx_slice = pd.IndexSlice
print("\nEngineering Seniors (via pd.IndexSlice):")
display(df_hierarchical.loc[idx_slice['Engineering', 'Senior'], :])

MultiIndex DataFrame:

                    Base_Salary  Bonus
Department  Level
Engineering Senior       150000  30000
            Mid          110000  15000
            Junior        80000   8000
Marketing   Senior       130000  25000
            Junior        70000   6000

All Senior Employees across departments (via .xs):

             Base_Salary  Bonus
Department
Engineering       150000  30000
Marketing         130000  25000

Engineering Seniors (via pd.IndexSlice):

Base_Salary    150000
Bonus           30000
Name: (Engineering, Senior), dtype: int64

### 10. SQL Window Functions in Pandas (`ROW_NUMBER`, `RANK`, `DENSE_RANK`, `NTILE`)
**Interview Question:** *How do you write the exact equivalents of SQL's `ROW_NUMBER()`, `RANK()`, and `DENSE_RANK() OVER (PARTITION BY Dept ORDER BY Salary DESC)` in Pandas?*

- **`ROW_NUMBER()`:** `df.groupby('Dept').cumcount() + 1`
- **`RANK()`:** `df.groupby('Dept')['Salary'].rank(method='min', ascending=False)` (leaves gaps after ties)
- **`DENSE_RANK()`:** `df.groupby('Dept')['Salary'].rank(method='dense', ascending=False)` (no gaps after ties)
- **`NTILE(N)`:** `pd.qcut(df['Salary'], q=N, labels=False) + 1`

In [158]:
# SQL Window Functions in Pandas
df_sql = pd.DataFrame({
    'Department': ['IT', 'IT', 'IT', 'IT', 'Sales', 'Sales', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Salary': [120000, 120000, 100000, 90000, 110000, 110000, 85000]
})

# Sort within partitions first:
df_sql = df_sql.sort_values(by=['Department', 'Salary'], ascending=[True, False]).reset_index(drop=True)

# 1. ROW_NUMBER()
df_sql['row_number'] = df_sql.groupby('Department').cumcount() + 1

# 2. RANK() - ties get same rank, skips next rank
df_sql['rank'] = df_sql.groupby('Department')['Salary'].rank(method='min', ascending=False).astype(int)

# 3. DENSE_RANK() - ties get same rank, does NOT skip next rank
df_sql['dense_rank'] = df_sql.groupby('Department')['Salary'].rank(method='dense', ascending=False).astype(int)

print("SQL Window Ranking Equivalents in Pandas:")
display(df_sql)

SQL Window Ranking Equivalents in Pandas:

  Department Employee  Salary  row_number  rank  dense_rank
0         IT    Alice  120000           1     1           1
1         IT      Bob  120000           2     1           1
2         IT  Charlie  100000           3     3           2
3         IT    David   90000           4     4           3
4      Sales      Eva  110000           1     1           1
5      Sales    Frank  110000           2     1           1
6      Sales    Grace   85000           3     3           2

### 11. Time-Series Deep Dive: Frequencies, Resampling & Business Days
**Interview Question:** *What is the difference between `.resample()` and `.asfreq()`? How do you calculate Month-End aggregates and forward-fill missing business days?*

- **`.resample('ME')`:** GroupBy-like aggregator over time windows (e.g. sum of sales for each month).
- **`.asfreq('B')`:** Resets the date index to fixed frequency intervals (e.g., business days Monday–Friday), inserting NaNs for missing days.

In [159]:
# Time-Series Resampling and Business Day Offsets
dates = pd.date_range(start='2026-01-01', end='2026-03-31', freq='D')
ts_df = pd.DataFrame({
    'Revenue': np.random.randint(1000, 5000, size=len(dates))
}, index=dates)

# Monthly Aggregations using .resample('ME'):
monthly_summary = ts_df.resample('ME').agg(
    Total_Revenue=('Revenue', 'sum'),
    Daily_Avg=('Revenue', 'mean'),
    Peak_Day=('Revenue', 'max')
)
print("Monthly Financial Summary via .resample('ME'):")
display(monthly_summary)

Monthly Financial Summary via .resample('ME'):

            Total_Revenue    Daily_Avg  Peak_Day
2026-01-31          92736  2991.483871      4669
2026-02-28          86369  3084.607143      4948
2026-03-31          85635  2762.419355      4958

### 12. Advanced Missing Data: Linear & Time-Based Interpolation
**Interview Question:** *Why is `.fillna(mean)` dangerous for time-series or sensor data? How do you use interpolation with limits?*

- Filling with constant or mean creates artificial plateaus that destroy volatility and trend patterns in financial/sensor metrics.
- `df.interpolate(method='time')` or `method='linear'` estimates missing points based on surrounding trajectory.
- Use `limit=N` to prevent filling over large missing stretches.

In [160]:
# Missing Data: Interpolation vs Mean Imputation
sensor_df = pd.DataFrame({
    'Timestamp': pd.date_range('2026-01-01 00:00', periods=7, freq='h'),
    'Temperature': [20.0, 21.0, np.nan, np.nan, 26.0, 28.0, 29.0]
}).set_index('Timestamp')

sensor_df['Linear_Interpolation'] = sensor_df['Temperature'].interpolate(method='linear')
sensor_df['Forward_Fill_Limit1'] = sensor_df['Temperature'].ffill(limit=1)

print("Sensor Imputation Comparison:")
display(sensor_df)

Sensor Imputation Comparison:

                     Temperature  Linear_Interpolation  Forward_Fill_Limit1
Timestamp
2026-01-01 00:00:00         20.0             20.000000                 20.0
2026-01-01 01:00:00         21.0             21.000000                 21.0
2026-01-01 02:00:00          NaN             22.666667                 21.0
2026-01-01 03:00:00          NaN             24.333333                  NaN
2026-01-01 04:00:00         26.0             26.000000                 26.0
2026-01-01 05:00:00         28.0             28.000000                 28.0
2026-01-01 06:00:00         29.0             29.000000                 29.0

### 13. High-Performance Vectorized Regex & Text Parsing (`.str` accessor)
**Interview Question:** *How do you extract structured entities (e.g., email user, domain, order ID) from unformatted text columns in Pandas without slow row-by-row loops?*

- Use `df['col'].str.extract(r'regex_with_capture_groups')` which returns a DataFrame directly in C-speed vectorized execution!

In [161]:
# Vectorized Regex Extraction
logs_df = pd.DataFrame({
    'raw_log': [
        'User alice@company.com completed order #ORD-9821 for $120.50',
        'User bob_smith@gmail.com completed order #ORD-4310 for $85.00',
        'User charlie.dev@tech.org completed order #ORD-6677 for $340.25'
    ]
})

# Extract username, domain, order_id, and amount in one vectorized call:
pattern = r'User (?P<user>[\w\.]+)@(?P<domain>[\w\.]+).*#(?P<order_id>ORD-\d+).*\$(?P<amount>[\d\.]+)'
extracted = logs_df['raw_log'].str.extract(pattern)
extracted['amount'] = extracted['amount'].astype(float)

print("Vectorized Entity Extraction:")
display(extracted)

Vectorized Entity Extraction:

          user       domain  order_id  amount
0        alice  company.com  ORD-9821  120.50
1    bob_smith    gmail.com  ORD-4310   85.00
2  charlie.dev     tech.org  ORD-6677  340.25

### 14. Classic Senior Interview Problem: Customer Retention & Cohort Analysis
**Interview Question:** *Given a transaction table `(customer_id, order_date, amount)`, calculate month-over-month cohort retention rates.*

**Algorithm:**
1. Determine each customer's first purchase month (Cohort Month).
2. Compute the month offset between transaction month and Cohort Month.
3. Group by `[Cohort_Month, Month_Offset]` and count unique active customers.
4. Pivot into a retention matrix and divide by initial cohort size.

In [162]:
# Cohort Retention Matrix
np.random.seed(42)
n_tx = 1000
tx_df = pd.DataFrame({
    'customer_id': np.random.randint(100, 200, size=n_tx),
    'order_date': pd.to_datetime('2026-01-01') + pd.to_timedelta(np.random.randint(0, 90, size=n_tx), unit='D'),
    'amount': np.random.uniform(20, 200, size=n_tx)
})

# 1. Invoice Month & Cohort Month
tx_df['order_month'] = tx_df['order_date'].dt.to_period('M')
tx_df['cohort_month'] = tx_df.groupby('customer_id')['order_month'].transform('min')

# 2. Cohort Index (Month Offset)
tx_df['cohort_index'] = (tx_df['order_month'].dt.year - tx_df['cohort_month'].dt.year) * 12 + \
                        (tx_df['order_month'].dt.month - tx_df['cohort_month'].dt.month)

# 3. Pivot retention table
cohort_data = tx_df.groupby(['cohort_month', 'cohort_index'])['customer_id'].nunique().reset_index()
cohort_pivot = cohort_data.pivot(index='cohort_month', columns='cohort_index', values='customer_id')

# 4. Retention Percentage Matrix
cohort_sizes = cohort_pivot.iloc[:, 0]
retention_matrix = cohort_pivot.divide(cohort_sizes, axis=0) * 100

print("Cohort Retention Rate (%):")
display(retention_matrix.round(1))

Cohort Retention Rate (%):

cohort_index      0      1     2
cohort_month
2026-01       100.0   94.8  96.9
2026-02       100.0  100.0   NaN